# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reactoragent < Formula
  desc "Supercharge your development server."
  homepage "https://nerderbur.tech"
  version "0.1.0-alpha"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha/reactoragent_0.1.0-alpha_Darwin_x86_64.tar.gz"
    sha256 "383362e2bd46e95b0d2b64ad99554e2f294d0ebb87736b813a5a423eb701888a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha/reactoragent_0.1.0-alpha_Darwin_arm64.tar.gz"
    sha256 "44abea37c9148edb45ca7a5040a0a4ca09e6683d32652909715b268254612876"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha/reactoragent_0.1.0-alpha_Linux_x86_64.tar.gz"
    sha256 "6f139e7894039524a1f58828f93f566fdf1ded503cef0b51736fe82c1a992883"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha/reactoragent_0.1.0-alpha_Linux_arm64.tar.gz"
    sha256 "dfa9333da7b40cf0024ed60b1682eb241319bd892bb517c5e19f2cd576d96e24"
  end

  def install
    bin.install "daemon"
    etc.mkpath
    mkdir "#{etc}/reactorapp"
    etc.install "config/example.conf" => "reactorapp/example.conf"
  end

  def caveats; <<~EOS
    1. Edit the example.conf file in /usr/local/etc/reactoragent
    2. Rename example.conf to default.conf
  EOS
  end
end
