# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reactoragent < Formula
  desc "Supercharge your development server."
  homepage "https://nerderbur.tech"
  version "0.1.0-alpha8"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha8/reactoragent_0.1.0-alpha8_Darwin_x86_64.tar.gz"
    sha256 "2c869530c4ffce28a59bdbc94b38e401b79ffe12bd5b5dd485ccce6679614f7b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha8/reactoragent_0.1.0-alpha8_Darwin_arm64.tar.gz"
    sha256 "0e047e5d823d2e1208b83f31341f1ab58d00d6a02d76fb72d9224f6fe15cff71"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha8/reactoragent_0.1.0-alpha8_Linux_x86_64.tar.gz"
    sha256 "76aa493eaaaf7c856b521247dc3a2b15000281cb458123b145f4440ca2bd30d0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha8/reactoragent_0.1.0-alpha8_Linux_arm64.tar.gz"
    sha256 "dffd34005491b180672a389b3d7152c44ba37af62600b496ea9aa8bf19c57b9e"
  end

  def install
    bin.install "daemon"
  end

  def post_install
    if !(File.exist?((etc/"reactoragent.conf"))) then
  prefix.install "config/example.conf" => "reactoragent.conf"
  etc.install_symlink prefix/"reactoragent.conf"
end

  end

  def caveats; <<~EOS
    1. Edit the default.conf file in #{prefix}
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
      <key>Label</key>
      <string>com.nerderbur.tech</string>

      <key>RunAtLoad</key>
      <true/>

      <key>KeepAlive</key>
      <true/>

      <key>ProgramArguments</key>
      <array>
          <string>/usr/local/bin/daemon</string>
      </array>

      <key>StandardOutPath</key>
      <string>/tmp/log/reactoragent.log</string>

      <key>StandardErrorPath</key>
      <string>/tmp/log/reactoragent.log</string>
  </dict>
</plist>

  EOS
  end
end
