# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reactoragent < Formula
  desc "Supercharge your development server."
  homepage "https://nerderbur.tech"
  version "0.1.0-alpha6"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha6/reactoragent_0.1.0-alpha6_Darwin_x86_64.tar.gz"
    sha256 "695fcd408c0cdb71fbb8fda37c24a4efaf8f02492a4766827fd7682adf22c0db"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha6/reactoragent_0.1.0-alpha6_Darwin_arm64.tar.gz"
    sha256 "221d249a55b2431408ee6d0866f9cd34c87b88844d7911b2a0604a43710eb0e3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha6/reactoragent_0.1.0-alpha6_Linux_x86_64.tar.gz"
    sha256 "b2aa3d187eb61bbee3e76a2f894178a016faf9aa21e28e448bf31f827817fad9"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/leonwright/reactor-agent/releases/download/v0.1.0-alpha6/reactoragent_0.1.0-alpha6_Linux_arm64.tar.gz"
    sha256 "d484f22eab69f8f92651376b251beadd2d79f05a1507201b493957e25ff847dc"
  end

  def install
    bin.install "daemon"
    prefix.install "config/example.conf" => "reactoragent.conf"
    etc.install_symlink prefix/"reactoragent.conf"
  end

  def caveats; <<~EOS
    1. Edit the default.conf file in #[prefix]
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
      <key>Label</key>
      <string>com.nerderbur.tech</string>

      <key>RunAtLoad</key>
      <true/>

      <key>KeepAlive</key>
      <true/>

      <key>ProgramArguments</key>
      <array>
          <string>/usr/local/bin/daemon</string>
      </array>

      <key>StandardOutPath</key>
      <string>/tmp/log/reactoragent.log</string>

      <key>StandardErrorPath</key>
      <string>/tmp/log/reactoragent.log</string>
  </dict>
</plist>

  EOS
  end
end
